version: "3"

services:
  gift-dev:
    image: steveoni/giftapi:1.0
    env_file:
      - .env
    ports:
      - "0.0.0.0:3000:5000"
    volumes:
      - /Users/steveoni/Downloads/gift-data-110ad1f62153.json:/tmp/keys/gift-data-110ad1f62153.json
  gift-db:
    container_name: gift-db2
    image: postgres
    env_file:
      - .env
    volumes:
      - pg_data1:/var/lib/postgresql/data2
volumes:
  pg_data1: