version: "3"

services:

  db:
    image: postgres:11.6
    volumes:
      - "db-data:/var/lib/postgresql/"
    environment:
      - POSTGRES_DBNAME=gift_api
      - POSTGRES_USER=gift_api
      - POSTGRES_PASS=gift_api

  web:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./:/srv/app
    environment:
      - DATABASE_URL=postgresql://gift_api:gift_api@db/gift_api
      - GOOGLE_APPLICATION_CREDENTIALS
      - BUCKET_NAME

volumes:
  db-data:
